### ISSUE TITLE
V1.0 errata

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#10]
- [x] add some PWR LEDs
- [x] fix footprint of BD5230. VSOT package has nothing to do with SOT-23. Use MSOP package pinout instead...

**Comment by hartytp** [comment]
@sbourdeauducq did you have concerns about using the microprocessor's in-build ADC for calibration of the TEC zero-point voltage? If so would you prefer to add an external ADC for this (12-bit should be fine)?
