### ISSUE TITLE
J11 connector is under FAN

### ISSUE THREAD

**Issue by maciejprzybysz** [sinara-hw/Thermostat#103]
This connector has no P/N nor 3D model, but assuming standard 2.54 goldpin there will be collision with the FAN during assembly.

![2021-10-26_14h28_26](https://user-images.githubusercontent.com/48446953/139917345-38caa7fa-da3e-4c68-b2cf-53cbd6f9c6dc.png)

**Comment by gkasprow** [comment]
It's DNP on purpose to directly solder fan wires

Pozdrawiam
G.Kasprowicz
________________________________
From: maciejprzybysz ***@***.***>
Sent: Tuesday, November 2, 2021 6:40:39 PM
To: sinara-hw/Thermostat ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sinara-hw/Thermostat] J11 connector is under FAN (Issue #103)


This connector has no P/N nor 3D model, but assuming standard 2.54 goldpin there will be collision with the FAN during assembly.

[2021-10-26_14h28_26]<https://user-images.githubusercontent.com/48446953/139917345-38caa7fa-da3e-4c68-b2cf-53cbd6f9c6dc.png>
