### ISSUE TITLE
replace PWM with a DAC

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#11]
I'd like to replace the PWM for the TEC controller with 16-bit I2C DACs with internal references like AD5693R to the next revision. Seems easier than fighting to squeeze the last bits out of PWM and won't make a significant impact on the board ownership. We can always re-visit PWM if we move to a custom TEC driver in a future revision.

Any objections?

**Comment by hartytp** [comment]
@gkasprow would you be happy dead-bugging this onto the current HW, or should I do that once you send it to me?

**Comment by gkasprow** [comment]
@hartytp sorry, I have higher priorities. I'm just moving all Sayma/Metlino designs to AD19. Mentor didn't agree to renew the Xpedition license for WUT. Once Siemens bought Mentor, the rules changed.
We still have a commercial license but it expires in March. After that, we won't have any. I got to know about it a few days ago... I will write another post about it.

**Comment by hartytp** [comment]
Ack no problem. Can you post me the boards then and I’ll make the changes.

First, any objection to adding DACs (@jordens)?

**Comment by hartytp** [comment]
@gkasprow to ensure that Thermostat works well for high dynamic range applications, let's go for an 18-bit DAC. 

AD5680 looks to be a good choice. 
- it's 18-bit monotonic, but only 16-bit accurate (e.g. large INL)
- typical offset voltage is approx 1 LSB at 12bits (although, abs max offset over PVT is specified to be about 8 times that). This seems fine.
- It does require an external reference. The reference doesn't need to have a low temp co or amazing low frequency noise/accurate since it's mainly intended to be used closed loop. So, pick any suitable buffered ref. 

Unless anyone objects, let's finalize that decision for the next hardware revision.

**Comment by hartytp** [comment]
Thinking about this a bit more, it's probably best to use the TEC driver's REF output for the DAC reference.
- the TEC has a low-accuracy, somewhat drifty reference. This sets the control voltage that gives 0 TEC current. For systems that use low TEC/heater currents, getting this right is quite important.
- our original plan was to use an ADC to calibrate the TEC driver reference using the reference output pin. This relies on having quite accurate ADCs in the microprocessor and uses a bit more software work.
- let's just use a cheap low-speed OpAmp in a small package like 5-pin SOT as a 2x buffer to cover the TEC reference to a DAC reference. That way most systematics common-mode out and we don't need to bother with software calibration or external references.
- If we do that, it makes sense to use a DAC with decent offsets/INL, so I'll pick a different PN

**Comment by jordens** [comment]
Are you sure the zero offset is critical? It only determines the proper reset value of the integrator and it is only as critical as accurate knowledge of the ambient temperature.

**Comment by hartytp** [comment]
> It only determines the proper reset value of the integrator and it is only as critical as accurate knowledge of the ambient temperature.

For TEC/heater currents that are larger than the offset, that's true. However, if the TEC/heater current gets smaller than the offset then the sign of the feedback gain changes, which can get a bit nasty (Thermostat thinks it's heating when it's actually cooling).

Anyway, this isn't an issue for any of the systems I have in mind, so I haven't put much thought into it.

> Thinking about this a bit more, it's probably best to use the TEC driver's REF output for the DAC reference.

Actually, I'm not sure this is worth the effort. To get decent accuracy, we'd need a resistor ladder/PGA and it's not at all clear that the gain would be worth it.

Once we have a PN for the microprocessor, we should check the accuracy of the ADCs and decide whether it's worth doing a power-on calibration of the TEC driver reference + DAC offset or not. This is a pretty low priority for me though.

**Comment by gkasprow** [comment]
we can assume same CPU PN as in the Stabilizer.

**Comment by hartytp** [comment]
Okay, those ADCs look pretty good. I suspect that if we measure the DAC offset with the same ADC as the TEC driver offset, the ADC offsets will common-mode out, so we should get a nice accurate measurement of the zero-point current without any clever tricks.

We could derive the DAC reference from the TEC controller to take out drifts/noise in the TEC controller reference after calibration, but I don't think it's worth the effort.

**Comment by jordens** [comment]
> For TEC/heater currents that are larger than the offset, that's true. However, if the TEC/heater current gets smaller than the offset then the sign of the feedback gain changes, which can get a bit nasty (Thermostat thinks it's heating when it's actually cooling).

I don't think so. This sounds like the typical wrong PID design (gain after integration instead of the other way around).

**Comment by hartytp** [comment]
Yes, you're right, it's not an issue. Anyway, it's not relevant for the use cases I have in mind, so wasn't putting enough thought into it. Glad you're paying more attention!

**Comment by gkasprow** [comment]
The CPU has 2 DAC output channels. Can we use them for something instead of PWM?

**Comment by gkasprow** [comment]
@hartytp What is the conclusion for driving the DAC reference? We will measure the TEC ref with CPU ADC?
I already connected it in such manned.

**Comment by hartytp** [comment]
Yes, let’s connect the tec driver ref to an ADC. Drive the dac ref from a buffered voltage reference.
