### ISSUE TITLE
add PDF for v1.0

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#13]
@gkasprow the only PDF of the current version I can find is https://github.com/sinara-hw/Thermostat/issues/4#issuecomment-436790828
Could you add one to the v1.0 release?

**Comment by gkasprow** [comment]
done.

**Comment by jordens** [comment]
I can't find it. And the v1.0 tag is not published as a release.

**Comment by hartytp** [comment]
@gkasprow is this done?

**Comment by jordens** [comment]
No.

**Comment by gkasprow** [comment]
The pdf is here
https://github.com/sinara-hw/Thermostat/releases/tag/v1.0rc1

**Comment by jordens** [comment]
That's not v1.0 and doesn't correspond to the v1.0 board I got at all.

**Comment by hartytp** [comment]
Yes it’s an dc. I don’t think there was ever a pdf for the production version

**Comment by hartytp** [comment]
@gkasprow please can we have a PDF of v1.0? The one in releases is still an RC and not the production version.

**Comment by gkasprow** [comment]
OK, I've just noticed that pdf was generated in the wrong location.
