### ISSUE TITLE
Check Poe isolation barrier

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#17]
Same as https://github.com/sinara-hw/Stabilizer/issues/15

**Comment by hartytp** [comment]
@gkasprow is this done?

**Comment by gkasprow** [comment]
Not yet, did not touch board routing. Let's review the schematics first.

**Comment by hartytp** [comment]
Okay that makes sense. I’d like to do some quick tests on existing hw before freezing the schematics.

**Comment by gkasprow** [comment]
fixed
