### ISSUE TITLE
5V ref compensation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#21]
The reference requires compensation when driving capacitive loads. See figure 33 of the datasheet https://www.analog.com/media/en/technical-documentation/data-sheets/adr430_431_433_434_435.pdf

I know that our capacitors are tantalum, but the frequency is quite low so I suspect it will still be an issue. Can we add the recommended compensation RC please?

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/63229871-551b7a80-c205-11e9-8d69-d5c991684f8e.png)
