### ISSUE TITLE
ic1 sw pins connection missing

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#24]
why aren't pins 10 and 48 tied together?

**Comment by hartytp** [comment]
@gkasprow answering my own question, I guess the reason is that there are two banks of SW pins on opposite sides of the IC and you don't want to route them together.

Also, I haven't checked the compensation for this reg, but assume you're happy with it?

**Comment by gkasprow** [comment]
I took the values from the datasheet.

**Comment by hartytp** [comment]
@gkasprow looking at the example layout (fig 6-1) the two sets of switch pins should be tied together with a thick trace.

**Comment by hartytp** [comment]
@gkasprow I didn't see much guidance in the data sheet on the choice of Cinj and Cff. It looks a bit like they have to be chosen empirically (depends a lot on the ESR of the capacitors used). Are you happy with the values there? Did you check the stability/noise of this regulator?

**Comment by gkasprow** [comment]
I took them from the [reference design](https://www.arrow.com/en/reference-designs/mic45116-1ymp-ev-evaluation-board-for-the-mic45116-1-20v6a-dc-to-dc-power-module/98683d59703926eaa41bfb0839684ba1)

**Comment by gkasprow** [comment]
I think I have to look at it once again and verify its stability with a step response test.
The sudden death of the 3V3 converter made me suspicious. I'm using this configuration in a few other designs and nobody complained so far but since a lot depends on load, who knows...

**Comment by gkasprow** [comment]
I can also do it with V2.0 since I don't have any thermostat in my hands.

**Comment by hartytp** [comment]
Happy to send you one if it would help?

**Comment by gkasprow** [comment]
I have other design with an identical converter so can use it for testing. 
I do a very simple test:
 Connect a scope and a pushbutton with a 2R/5W resistor in series.
One probe goes to the switch, another to the power rail. Then trigger on falling and rising edge and observe the response. It cannot oscillate. If it does, there are stability issues.

**Comment by hartytp** [comment]
Good idea. FWIW I think we’re running at a quite light load, not sure how that impacts stability

**Comment by hartytp** [comment]
@gkasprow are you happy the layout for this ic follows the reference design?

**Comment by gkasprow** [comment]
yes.
