### ISSUE TITLE
DAC PWM

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#26]
@jordens did you want a FET that can be used to PWM the DAC output?

**Comment by jordens** [comment]
That would be useful. Yes. Before the rc filter (can be DNP if it's not needed for the dac) from v1.0

**Comment by hartytp** [comment]
I'm fine with that so long as someone thinks through the usual things like Ron etc to make sure that it won't degrade the performance when not used.

**Comment by hartytp** [comment]
NB the DAC is really a 16-bit DAC with an internal modulator/interpolator. So we're already doing a scheme like that at a very basic level...

**Comment by gkasprow** [comment]
just FET or analog switch?
FETs have high charge injection unless you take one of [these](http://www.calogic.net/pdf/SST211_Datasheet_Rev_A.pdf)

**Comment by hartytp** [comment]
ill Leave that decision to @jordens fwiw though I don’t think charge injection is an issue due to the 2 pole rc filter (we’re doing pwm so need a good filter)

I assume well so something like have a 1k resistor after the dac and then a shunt fet.

To check though, the charge injection is only an issue when the fet switches right, not when it’s static?

**Comment by jordens** [comment]
With that 18 bit DAC and 1 LSB DNL it's fine. Plenty of resolution even for small loads. No need for the FET to PWM-multiply the DAC output.

**Comment by jordens** [comment]
Really interesting DAC by the way. Nice for high resolution low noise actuators inside slowish control loops.

**Comment by gkasprow** [comment]
Yes, Moreover charge injection is usually symmetrical so the avarage charge is 0.
