### ISSUE TITLE
DAC reference

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#27]
@gkasprow shouldn't we use a 3V reference for the DAC to match it to the TEC driver? Currently we're throwing away nearly an entire bit of resolution by using the wrong reference.

**Comment by gkasprow** [comment]
True. We can also add resistive divider but the reference is probably cheaper.

**Comment by hartytp** [comment]
Nb the dac still needs a decent 5V rail as it doesn’t support 3V vcc

**Comment by hartytp** [comment]
> True. We can also add resistive divider but the reference is probably cheaper.

Actually, we can probably get away with a divider made from 0.1% resistors. After all, the DAC offset is 10mV, which is 0.3%, so a small error on the reference won't harm us.

**Comment by hartytp** [comment]
And, DAC gain accuracy is only 1.5% so no point having an ultra-precise reference.

The main worry I'd have would be the higher reference impedance degrading the DNL. @gkasprow am I right in thinking that for this kind of resistor string DAC, that shouldn't be a problem since the ref current is constant? Or do we need a proper buffered reference here?

**Comment by gkasprow** [comment]
@hartytp AD5680 has already buffered output. So we can add resistors.

**Comment by hartytp** [comment]
Won’t it be an issue that the ref impedance at the ac will be high due to the resistors? Doesn’t the dac need a low impedance red?

**Comment by gkasprow** [comment]
Oh, I was thinking about adding voltage divider at the DAC output to match the range.

**Comment by gkasprow** [comment]
we can also use the ADC 3.3V supply as a reference.

**Comment by hartytp** [comment]
Aah ok. So long as the tec and cpu ADC inputs are high z, a divider on the dac output sounds like the best option

**Comment by gkasprow** [comment]
MAX1968 has 1MOhm input resistance. We don't really care about DC accuracy. So resistive divider in order of 1k should be fine.

**Comment by hartytp** [comment]
Sounds good
