### ISSUE TITLE
mesaure DAC output on microprocessor

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#28]
@sbourdeauducq should we wire the DAC output to a microprocessor ADC input? The DAC only has 12-bit accuracy (10mV offset), which is comparable to the TEC driver. No point calibrating the TEC if we don't calibrate the DAC as well.

**Comment by hartytp** [comment]
This also means we're not sensitive to offsets in the microprocessor ADC since they common-mode out on the two measurements (we're effectively finding the DAC word that makes the DAC output equal to the TEC ref value).

**Comment by gkasprow** [comment]
>  The DAC only has 12-bit accuracy (10mV offset)

Do you mean the CPU ADC?

**Comment by hartytp** [comment]
No the 18 bit DAC is only 12 bit precise as it’s designed for in loop applications like this. 18 bit accurate dacs cost $$$ this one is cheap. Stability and noise are good so it’s fine for our application

**Comment by hartytp** [comment]
CPU ADC offsets don’t matter so long as we measure the dac outputs and tec ref on the same ADC

**Comment by gkasprow** [comment]
I added another RC to isolate the DAC from the CPU ADC sampling current pulses

**Comment by hartytp** [comment]
When did you add that?

**Comment by gkasprow** [comment]
a few seconds ago.
![obraz](https://user-images.githubusercontent.com/4325054/60214997-02f25480-9867-11e9-84ab-0b7e782aef43.png)

**Comment by hartytp** [comment]
Did it make any difference?

**Comment by hartytp** [comment]
In the first instance, let's try to focus on allowing you to reproduce my results on an unmodified board. See if you can get +10V on channel 0 and -10V on channel 1 by flashing according to Robert's instructions. If not, I'll have another look at the FW I sent you in the morning.

**Comment by gkasprow** [comment]
It's thermostat issue, not stabilizer :D

**Comment by hartytp** [comment]
:) sorry. Doing too many things at once

**Comment by hartytp** [comment]
Looks good

**Comment by jordens** [comment]
When using the DAC and PWM Vref calibration values that you would obtain from this, I'd be very careful what to do with them. Initial one-time offset calibration, monitoring and correcting the limit PWMs later on are fine. But I don't think repeated feedback of those values onto the Iset DAC output are a good idea.

**Comment by hartytp** [comment]
@jordens yes I’d go for a power on cal and leave it there.
