### ISSUE TITLE
PoE AT detection

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#30]
For compliant operation the device can't pull more than 15.4 W unless we detect that we are allowed to. We are several watts above that limit and during the typical turn on transients when the thermal masses are cooled/heated from room temperature that limit will typically be exceeded.
The behavior if we don't detect it properly is guaranteed to be confusing (PSE trip).
What about putting the optocoupler and the AT detect pin to the CPU?

**Comment by gkasprow** [comment]
Good idea. We already did that for another [project.](https://github.com/BerkeleyLab/Marble/releases)

**Comment by gkasprow** [comment]
shall we do the same for Stabilizer? With mezzanines, we may exceed 15.4W

**Comment by jordens** [comment]
Yes same for stabilizer
