### ISSUE TITLE
2.5v reference

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#32]
Can't we just use the ADC's REFOUT? In my reading of the datasheet it is available independent of the external reference. Would save a BOM line.

**Comment by gkasprow** [comment]
True, one needs only to make sure that 3V3 wakes up first. But can be easily ensured by connecting IC6 EN to 3V3.

**Comment by hartytp** [comment]
You mean use the ADC 2V5 reference output for the microprocessor? How does that refout behave when using an external 3V3 reference? Other than that, seems like a good idea to me so long as it doesn't make the routing harder or risk noise issues by hooking the ref output to the microprocessor.

**Comment by gkasprow** [comment]
Added. But I left the original reference as DNP
