### ISSUE TITLE
ADC: hook up SYNC and CLKIO to µC

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#33]
* to actively align the ADC sampling to µC timing/external timing
* to drive the adc clock from a uC timer

**Comment by gkasprow** [comment]
Which CPU pins shall I use?
Timer output?

**Comment by jordens** [comment]
yes both can be timer outputs of different channels of the same timer.

**Comment by gkasprow** [comment]
connected PD12, PD13
