### ISSUE TITLE
combo footprints for IDC J1/J3 and green rear connectors J4/J5

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#34]
since the are not being used at the same time, i would only mount one of them. that works well with the already existing variants of it being in a 3U format (then J1/J3) or the enclosure (J4/J5). and it may be a significant space saver on the crowded board.

**Comment by hartytp** [comment]
If it makes the layout better/easier/smaller then fine. However, I like having both there by default, since we will use both in different circumstances, so nice to have a single set of boards that can be used in either way without modification.

**Comment by gkasprow** [comment]
we won't gain any additional space.
