### ISSUE TITLE
4 front panel LEDs

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#35]
Can we use the same 4 way LED stack that we have on e.g. Zotino (either 4 green or 2 green+2 red) instead of just two LEDs? Looks like it should fit space-wise and it would provide much needed detailed status monitoring funtionality.

**Comment by hartytp** [comment]
Sounds good, particularly if we can go for 2G and 2R

**Comment by gkasprow** [comment]
sure, let's go for it.
