### ISSUE TITLE
Peltier voltage measurements

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Thermostat#37]
I would connect the Peltier outputs to CPU ADC channels so that the Peltier voltage can be measured. That allows power calculation, better monitoring, and comprehensive characterization of the control loop (thermal mass, thermal resistance).

**Comment by jordens** [comment]
Also connect the Vref+, 5V, and 12V rails to the CPU ADC (with a divider if necessary) for monitoring.

**Comment by hartytp** [comment]
Good idea

**Comment by gkasprow** [comment]
Due to lack of ADC inputs, I used diff amps.
![obraz](https://user-images.githubusercontent.com/4325054/63229762-37014a80-c204-11e9-835c-f025eeba4598.png)
