### ISSUE TITLE
mechanical issues

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#41]
@gkasprow did you fix the mechanical issues that prevent v1.0 fititng into the Hammond enclosure? IIRC the PoE module is a bit close to the edge and there is a large capacitor blocking.

**Comment by jordens** [comment]
#16

**Comment by hartytp** [comment]
Thanks! Somehow I missed that when I looked for it.

**Comment by gkasprow** [comment]
I shifted it by 1mm
