### ISSUE TITLE
v1.0 analog tests

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#46]
Tests I propose to do:
- [ ] TEC driver at 0 current (no load) use a 10k precision resistor instead of thermistor and measure noise/stability . Put the resistor as close to thermostat as possible to limit room for pickup
- [ ] same as previous but put the resistor at the end of a few m of screened twisted pair cable
- [ ] same as previous, but with the TEC set to a few different currents between +- full-scale (using a resistor as a load)

I think that will be enough to verify the basic functionality before finalizing the v2.0 design, but let me know if anyone thinks there is anything else we should do.

**Comment by jordens** [comment]
When doing the last one, do it with PoE, both TEC drivers at full current and use the opportunity to take a couple thermal camera photos. That would yield a lot of info on #38 .

**Comment by hartytp** [comment]
> When doing the last one, do it with PoE, both TEC drivers at full current 

How much power can the PoE supply in v1.0?

Otherwise, sure, if I can track down a thermal camera I'll do that.

**Comment by jordens** [comment]
Full beans. 25.5W to the device. But even with external 12V it would be useful if you don't have 803.2at.

**Comment by hartytp** [comment]
Okay, I'm not up to speed on this, but I though that required the AT detect line doesn't it? Or does that just tell the CPU what power is available?

Okay, I'll see how much juice my PoE switch has and run this as hard as possible from both sources.

**Comment by jordens** [comment]
The AT line is just for letting the CPU know that it is allowed to draw that much.

**Comment by hartytp** [comment]
![image](https://user-images.githubusercontent.com/21218399/64681669-0c5b8800-d478-11e9-8d33-af4a90bb6206.png)

@jordens doesn't this imply that the firmware usually needs to do something to enable >15W of power from the switch?

**Comment by jordens** [comment]
Where does it say that?
Classification is negotiated between PSE and PD (the module) and then signaled to the CPU via AT. There is nothing the CPU can do.

**Comment by hartytp** [comment]
In the docs I pasted above, the module states that the controller needs to negotiate Type 2 PD over the data link layer. As I understood it the "controller" here is the microprocessor, not the PoE module. The PoE module doesn't touch the data layer, right, since that goes on separate wires to the phy. Anyway, it's also very possible that I'm misunderstanding the basic terminology here...

**Comment by jordens** [comment]
Ah. That's LLDP over Ethernet for data layer classification (DLC) as opposed to physical layer classification only which we are doing. I am a bit unsure about the standard and when DLC for type 2 is a must. The datasheet calls it a "should".
The switches I have (but no Cisco) don't need DLC.

**Comment by hartytp** [comment]
Okay, well may or may not be an issue for the switches people want to use. But worth bearing in mind.

**Comment by jordens** [comment]
Yes. If this turns out to be a problem or desirable feature, then implementing LLDP DLC doesn't look to complicated.

**Comment by hartytp** [comment]
Taking prelim data (will post in morning) but RMS noise is about 2LSB with PoE, not bad!

Assume thermistor is `dR/dT = 4.4e-2/K`. Thermistor voltage is approx `V_th=Vr/2`, `1LSB = Vr/2^24 = Vth/2^23=5nK`

![image](https://user-images.githubusercontent.com/21218399/65177531-c0e44380-da4e-11e9-969c-67b9f49e2311.png)

**Comment by hartytp** [comment]
![image](https://user-images.githubusercontent.com/21218399/65178130-02c1b980-da50-11e9-8d2e-832debb80d53.png)

rms noise is about 15nK, pk to pk is 0.1uK

**Comment by hartytp** [comment]
Nice! Impressive it works so well with PoE!

**Comment by jordens** [comment]
That's really good.
What's the limit here? If I am not wrong, this meets the datasheet (16 S/s with the 50 Hz filters: ~0.5µVrms ~2LSBrms).

**Comment by hartytp** [comment]
Yes @jordens my understanding is that this measurement is roughly consistent with the noise floor of the ADC with the filters we've chosen and the buffers enabled. Not going to gaurantee that's still going to be with case with the TEC drivers at full whack however.

What's interesting is that upping the output data rate doesn't really affect the noise floor, only the 50Hz rejection. even then, in most cases the noise floor could be quite a bit higher without issue, so there is room for users to trade off loop bw for noise rejection if they desire...

**Comment by jordens** [comment]
Exactly. 16 S/s and a couple Hz loop bandwidth would be slow for small and tightly coupled thermal loads. And 0.1µK would be too good.  ;)

**Comment by pathfinder49** [comment]
I've logged the ADC reading for a longer duration. The measurement was done in an office environment with a lot of electronics running in the surrounding and no temperature stabilization.

The board was powered using PoE from the ProSAFE JGS516PE and the programmer was connected to a computer. The thermistor was replaced with a 10k reference resistor

![PoE short LSB](https://user-images.githubusercontent.com/14295481/65261058-5b9c5b00-daff-11e9-977f-c404caafb8c0.png)

![PoE short](https://user-images.githubusercontent.com/21218399/65260094-b8971180-dafd-11e9-9456-008af1caf6b9.png)

The room was vacated from about 6000 s to 11500 s. During this period the ambient temperature was significantly increased due to poor ventilation. I'd estimate the temperature increased by over 5 K. 

All in all this looks promising.

**Comment by jordens** [comment]
What's `np.diff(data).std()/2**.5` for that (cheap trick for suppressing the low-f instability of normally distributed noise)?

**Comment by pathfinder49** [comment]
> What's `np.diff(data).std()/2**.5` for that (cheap trick for suppressing the low-f instability of normally distributed noise)?

in units of LSB 2.51

**Comment by gkasprow** [comment]
Would the on-board temperature sensor make sense to compensate for  ADC temperature coefficient?

**Comment by pathfinder49** [comment]
Here is a 10 minute run using the power jack and with the programmer disconnected.

![Jack short LSB](https://user-images.githubusercontent.com/14295481/65263415-84731f00-db04-11e9-9ec7-3286bce76d36.png)


This gives np.diff(data).std()/2**.5 = 2.55

**Comment by pathfinder49** [comment]
The same as before, but using a 3 m twisted pair to connect to the 10k reference resistor. 

Powered via jack and programmer disconnected. (np.diff(data).std()/2**.5 = 2.57)

![Jack cable LSB](https://user-images.githubusercontent.com/14295481/65265052-ec773480-db07-11e9-9c7f-9481ba7fed4b.png)


Powered via PoE and programmer connected. (np.diff(data).std()/2**.5 = 2.53)
![PoE cable LSB](https://user-images.githubusercontent.com/14295481/65271438-13883300-db15-11e9-9292-1cff8ad3b695.png)

**Comment by hartytp** [comment]
> Would the on-board temperature sensor make sense to compensate for ADC temperature coefficient?

**Comment by hartytp** [comment]
> Would the on-board temperature sensor make sense to compensate for ADC temperature coefficient?

The ADC has a temperature sensor inside it that can be read out (at the expense of a 30% reduction in data rate). It would then be trivial to compensate the temperature coefficient in software, although it would probably have to individually measured for each board.

Based on the expected temperature coefficient for the circuit, and from the data posted above, my expectation is that the temp co will be low enough that users won't want to bother compensating it.

The caveat will be that if the TEC drivers make the board temperature vary strongly with the TEC current due to poor thermal management, then this might become an issue. But, hopefully with decent thermal management we can make this a non-issue.

**Comment by hartytp** [comment]
> Exactly. 16 S/s and a couple Hz loop bandwidth would be slow for small and tightly coupled thermal loads. And 0.1µK would be too good. ;)

Indeed. Obviously, if we want an easy factor of 2 in bw, we could switch to using 2 single ADCs instead of a dual. IME it's not worth it, since the control loops one wants are generally quite slow, but I'm happy to be corrected if that's not true for other people's use cases.

**Comment by hartytp** [comment]
> The same as before, but using a 3 m twisted pair to connect to the 10k reference resistor.

NB this cable was completely unscreened. 

That's great! This is one of the things that really worried me. Using COTS temperature controllers (including some quite expensive ones sold by laser companies whose electronics design skills I generally hold in high regard) I've generally found really poor results with long unscreened cables. Sometimes instability over a few minutes of 100mK or moor, presumably due to rectified RF/50Hz/whatever. It's great to see this working so well in a noisy environment with shoddy cabling!

**Comment by hartytp** [comment]
NB we were sloppy with our maths above and got the temperature conversion wrong. it's approx 5uK per LSB, not 5nK / LSB ... oops...

typical 10k thermistor:
```
- R_0 = 10k [Ohm]
- alpha = 4.4e-2 [K^-1]
- dR_th/dT = R_0*alpha [Ohm/K]
```

AFE:
```
- R = 5k
- V_th = V_r*R_th/(R_th+2*R)
- dV_th/dR_th = V_r*2R/(R_th+2R)^2
- R_th ~ R0 = 2R => dV_th/dR_th = V_r/(4*R0)
- dV_th/dT = dV_th/dR_th * dR_th/dT = V_r/(4*R0)*R0*alpha = V_r/4 * alpha
- ADC_mu = V_th/V_r*2^24
- dADC_mu/dT = dADC_mu/dV_th *d_Vth/dT = 2^22*alpha [LSB/K^-1]
- dT/dADC_mu = 1/(2^22*alpha) = 5.5uK / LSB
```

So the RMS noises we're looking at are more like 2.5LSB=14uK. So, still solidly respectable.

**Comment by pathfinder49** [comment]
I've done some more measurements with different post-filter settings:

Using the fastest sampling of 27 SPS I measure `np.diff(data).std()/2**.5` = 3.1 LSB.
The slowest sampling 0f 16.67 SPS gives `np.diff(data).std()/2**.5` = 2.5 LSB.

Removing the post-filter and sampling at a nominal 31,250 SPS I found `np.diff(data).std()/2**.5` = 259 LSB.


Edit:
Setup
Looking on both channels with a 10k precision resistor. One on a 2 m cable (twisted pair). No significant differences were observed.
TEC disconnected
Barrel connector powered. 

Nb I'd take the no-post-filter data with a pinch of salt. The ethernet data-stream experienced corruption at high data rates. I believe I've rejected all corrupt data.

**Comment by hartytp** [comment]
Thanks @pathfinder49 . Remind me (and yourself when you look back at this later on) what the setup was here? I assume something like:
- looking at channel 0
- both TECs disconnected
- powered from the barrel connector
- precision 10k resistor used instead of thermistor
- short cable? Or long unscreened (this is critical in terms of how much pick up we expect) cable? Otherwise "typical lab environment" on a desk next to a PC (decent EMI source)

How did the data look? By eye, did it look like white noise (did you FFT it quickly?) or did it look like it had structure? One thing I'm interested in is whether we see sudden spikes/glitches in the data due to EMI when less aggressive filtering is used.

Generally, how does this data compare with your expectations?

NB As before, conversion is approx 5.5uK/LSB

**Comment by hartytp** [comment]
Answering one of my own questions...for sine1+sine5 filter, no post filter, the datasheet says

![image](https://user-images.githubusercontent.com/21218399/67984241-3fbbc700-fc1e-11e9-8bf7-fa6269b618b1.png)

For a 3V3 reference, 260LSB RMS is 51uV RMS. That's a lot higher than the 9.5uV in the spec sheet, so seems a little suspicious. Would be interesting to see a noise spectrum, since I can imagine this is dominated by narrow-band sources (most likely 50Hz harmonics or SMPS noise).

For the data with post filter, 3.1LSB is 0.6uV RMS which is pretty close to the datasheet value

![image](https://user-images.githubusercontent.com/21218399/67984311-59f5a500-fc1e-11e9-9989-4f4098f05417.png)

So, it looks like there may be some scope for upping the sample rate, although the optimal is likely to be strongly dependent on the application.

Anyway, nice work.

**Comment by hartytp** [comment]
Oh, the other question I had was how long you recorded the data for. i.e. did you take 30min or so of data so you'd have a decent run at capturing somewhat infrequent noise spurs (the kind that wreak havoc with the COTS temperature controllers we have in the lab)

**Comment by pathfinder49** [comment]
> Remind me (and yourself when you look back at this later on) what the setup was here? 

I'll edit my post. 

> Oh, the other question I had was how long you recorded the data for. i.e. did you take 30min or so of data so you'd have a decent run at capturing somewhat infrequent noise spurs 

This data was over 2 minutes with post filter and 10 s without. 

Would you like additional long term data to that produced in sept?

**Comment by hartytp** [comment]
> Would you like additional long term data to that produced in sept?

Not long term data. I'd like two things:
- a noise spectrum for the data without post filter. The RMS noise is way above the data sheet for the ADC, so I suspect non-white noise e.g. due to unfiltered 50Hz. It would be interesting to confirm that
- A plot of the 10s of data without filtering. My potential concern here would be that without the filtering there might be worse low-frequency noise due to aliasing. Would be interesting to see whether that's the case, or if the noise looks high-frequency. Essentially, I just want to eye ball 10min-30min (or something like that) and check there are no large spikes or large drifts in the baseline. Just sanity checking.

**Comment by pathfinder49** [comment]
Apologies for the delay, here are some quick plots of the unfiltered data. The actual data rate was significantly less than the nominal 31,250 SPS from the filter settings. I haven't checked how the firmware handles time-stamping. So I'd take the frequency axis with a pinch of salt. The long cable was on ch0.

Raw data on one channel
![firmware filter None SPS](https://user-images.githubusercontent.com/14295481/68385129-040a8b00-0151-11ea-8b54-99d5f22c45ca.png)

FFT
![firmware filter None SPSfft](https://user-images.githubusercontent.com/14295481/68385146-0b319900-0151-11ea-82ac-1f3251d9cc06.png)

Zoomed on lower frequency range
![firmware filter None SPSfft_zoom](https://user-images.githubusercontent.com/14295481/68385181-1684c480-0151-11ea-9ec4-7527184ab61d.png)

**Comment by hartytp** [comment]
Thanks @pathfinder49 ! If the current firmware can't keep up with the ADC then I don't think the spectra are particularly meaningful, so I wouldn't read too much into the data. As I said, my guess is that with the wider BW and no screening around the board, we're dominated by pickup at various frequencies...

----

At a high level: clearly there is going to be an application-specific trade off on filter settings (more bw gives potentially better rejection of external thermal noise but worse rejection of electrical noise).

I think we've got enough data on that for now to demonstrate that the hardware doesn't seem to have any major issues. I suggest we leave this there for now and move onto the TEC.

**Comment by pathfinder49** [comment]
Here is a plot showing the adc response to step changes in the TEC 0 driver. Logging at 27SPS

The TEC current was stepped by setting the I-Set voltage as follows: 1.65 V (0.30 A) -> 2.97 V (2.94 A) -> 1.65 V -> 2.64 V (2.28 A) -> 1.65 V

TEC1 was left at 1.65 V

The ADC setup is the same as in previous posts and the board is powered via the 12 V jack.

![TEC steps postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68490891-b3bf2600-0241-11ea-8a72-68f883d521d8.png)

**Comment by hartytp** [comment]
Nice job @pathfinder49 . Let's see.
- `1LSB=5.5uk`
- `dV_tec = 1.3V`
- `dI_tec/dV_tec = 6A/3V=2A/V`
- So we have an approx 2.6A step in TEC current giving a `55LSB=0.3mK` change in the set-point. i.e. 110uK/A cross-talk between the set-point and the TEC current
- Similarly for an approx 2A step in TEC current giving a `25LSB=0.14mK` change in the set-point. i.e. 70uK/A cross-talk between the set-point and the TEC current

What's interesting is that the difference in the size of the two current steps is pretty small -- and the system doesn't exhibit any obvious hysteresis -- but there is a big difference in the size of the ADC offset change. So, there is something quite non-linear going on here. Maybe an issue with the supply voltage?

**Comment by hartytp** [comment]
either way, it suggests that for lower TEC powers the short-term (i.e. not worrying about board heating up yet) stability effects aren't huge.

Also, good to see that by eye there is no change in the short-term noise levels with the TEC on / off, which is also great!

**Comment by hartytp** [comment]
For completeness, I guess your set-up is:
- one TEC channel disabled, using the other one
- 1 Ohm resistor instead of a TEC
- 10k precision fixed resistor instead of a thermistor
- using the ADC post-filter with the highest possible sample rate (~20Hz IIRC)

Is that all correct? And, do you agree with my analysis above?

**Comment by pathfinder49** [comment]
Same data with the second channel shown

![TEC steps postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68494041-9be9a100-0245-11ea-8d50-d51f7b1e5238.png)

**Comment by gkasprow** [comment]
It can be caused by groundind loop. In the next revision I used 4 layer board where grounding is much better.

**Comment by pathfinder49** [comment]
@hartytp and I just measured the Voltage rails when stepping the TEC and could see no significant changes (1mV resolution DMM) on 5V5, 3V3, 3V3A or the resistor voltage drop.

**Comment by pathfinder49** [comment]
I've now repleaced the long leaded resistor on ch0 with one directly connected to the terminal block. The setups for ADC 0 & 1 are now identical. 

The plot shows the following TEC steps: [Note: current in A = 2*(voltage -1.5 V)]

- initially ch 0 & 1 @ 1.65 V
- Then the following changes were made in 10 s intervals unless specified. 
  - ch 0: 1.98 V (unit omitted from here) @ 10 s
  - ch0: 1.65 @ 20 s
  - ch0: 2.31 @ 30 s
  - ch0: 1.65 @ 40 s
  - ch0: 2.64 @ 50 s
  - ch0: 1.65 @ 60 s
  - ch0: 2.97 @ 70 s
  - ch0: 1.65 @ 80 s
  - ch0: 1.32 @ 90 s [smaller than 1.5 V -> negative current]
  - ch0: 1.65 @ 100 s
  - ch0: 0.33 @ 110 s
  - ch0: 1.65 @ 120 s
  - allow 30 s for thermal settling
  - ch1: 2.31 @ 150 s
  - ch1: 1.65 @ 160 s
  - ch1: 2.97 @ 150 s
  - ch1: 1.65 @ 160 s
  - allow 30 s for thermal settling
  - ch0&1:  2.31 @ 210 s
  - ch0&1: 1.65 @ 210 s
![TEC steps v3 postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68500130-c1c97280-0252-11ea-85db-fbad0249d270.png)

**Comment by hartytp** [comment]
@pathfinder49 so, I think the remaining tests in rough order of priorities are:
- [x] see if we can fix the ADC offset dependence on TEC current by adding some capacitors before the diodes/removing the diodes
- [x] repeat the ADC offset v TEC current when powering from POE (also try get verify that the noise RMS doesn't change as a function of TEC current)
- [ ] get some thermal camera images of both sides of the PCB when powering from PoE with both TECs near max (1Ohm loads)
- [ ] see what component is causing the shutdown at high TEC currents
- [ ] measure board temp co

If we can get all of that done, I'd say we've tested this design very well!
- [ ]

**Comment by pathfinder49** [comment]
I've added the capacitors you suggested (100 nF) on both adc channels. Performing the same measurement the behavior is broadly speaking the same.

![TEC steps with caps postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68630292-bd18ee80-04de-11ea-9d7f-37857d8521d9.png)

**Comment by pathfinder49** [comment]
I've connected the ADC REF- to the GND side of R50. 
![Screenshot from 2019-11-12 14-13-44](https://user-images.githubusercontent.com/14295481/68678860-ad3cf100-0556-11ea-923d-5de044150731.png)

This removes the stepping better than one LSB.
![TEC steps ch1 grounding postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68678798-8bdc0500-0556-11ea-9ad3-826f79070838.png)

On a separate note the ADC pin 1 appears to not be connected to ground on my board. This disagrees with the schematics.

**Comment by hartytp** [comment]
Awesome, so no short-term glitches evident at all when we step the TEC current -- just slow thermal effects. Very good!

**Comment by pathfinder49** [comment]
A quick attempt at getting noise characteristics at different TEC drive powers. The settling time is quite long, I'll follow up with a longer settling time.

Setup:
- using PoE
- TECs driving 1 Ohm resistors
- ADCs connected to 10 kOhm reference resistors
- ch1 has modified grounding
- 27 SPS

TEC settings (ch 0 & 1 are both kept at the same current)
initially: 0.6 A
600 - 1200 s: -0.4 A (each)
1200 - 1800 s: -1.4 A (each)
then 0.6 A (each)
![PoE TEC noise ch1 grounding postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68696661-4c70e100-0575-11ea-976a-a7fa4929d58e.png)

**Comment by hartytp** [comment]
Nice. So, am I right in saying that:
- with the star ground/kelvin connection we no longer see any glitches/offset changes on the ADC due to the TEC current (although there are slower thermal effects)
- to within a a factor of two, the RMS noise doesn't change depending on whether PoE/barrel connector is used and what the TEC current is? With the post filter on, it's always a few LSB RMS

If so, I think we're done with noise measurements. Just need to look at the temp co and board temperature and we're finished.

**Comment by pathfinder49** [comment]
For both channels driving a -2.0 A current and 27 SPS: (The board was disturbed several times during the measurement period)

![PoE TEC noise 2_6 A ch1 grounding postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68700948-bd1bfb80-057d-11ea-9b2c-1b47f9763087.png)

![PoE TEC noise 2_6 A ch1 grounding postfilter_27_SPSstd](https://user-images.githubusercontent.com/14295481/68700942-b9887480-057d-11ea-8549-7aee3096c2e9.png)


The board got extremely hot during this measurement. The inductors and TEC divers were observed exceeding 100°C. The ADC was at 60-70°C.

**Comment by pathfinder49** [comment]
Now with the TEC enabled, but set to drive 0.6 A: (using PoE)

![PoE TEC noise 0_0 A ch1 grounding postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68704323-08d1a380-0584-11ea-966e-2dcf3618eda0.png)
![PoE TEC noise 0_0 A ch1 grounding postfilter_27_SPSstd](https://user-images.githubusercontent.com/14295481/68704331-0bcc9400-0584-11ea-8acc-0a6c3f3175f1.png)

**Comment by hartytp** [comment]
Cool. So the noise is basically the same with PoE and barrel connector and doesn’t change with the tec current?

**Comment by pathfinder49** [comment]
> Cool. So the noise is basically the same with PoE and barrel connector and doesn’t change with the tec current?

The noise is TEC current dependent. For 2 A the noise is about 2x that of 0.6 A

**Comment by hartytp** [comment]
Really? here it looks like the noise is constant across changing TEC currents... https://github.com/sinara-hw/Thermostat/issues/46#issuecomment-552671356

**Comment by pathfinder49** [comment]
> Really? here it looks like the noise is constant across changing TEC currents... [#46 (comment)](https://github.com/sinara-hw/Thermostat/issues/46#issuecomment-552671356)

It's the only difference between my two most recent measurements.

**Comment by pathfinder49** [comment]
I've had a quick look at the noise TEC relation and it seems like it might be thermal.

I've measured stepping both TEC currents from 0 A -> 1 A (@ 600 s) -> 2 A (@ 1200 s) -> 0 A (@ 1800 s)
As the noise seemed structured I covered the ADC with paper for the second data-set below. This appears to reduce noise when driving large TEC currents.

The board was powered from PoE

ADC data

![PoE TEC noise 0 1 2 0 A ch1 grounding postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68786884-7212ee80-0638-11ea-9b61-733c49f1e622.png)

Floating standard deviation
![PoE TEC noise 0 1 2 0 A ch1 grounding postfilter_27_SPSstd](https://user-images.githubusercontent.com/14295481/68787023-a8e90480-0638-11ea-92cb-2794adacf624.png)


ADC covered by paper

![PoE TEC noise 0 1 2 0 A adc covered ch1 grounding postfilter_27_SPS](https://user-images.githubusercontent.com/14295481/68786818-560f4d00-0638-11ea-82a9-15e6ec197943.png)


![PoE TEC noise 0 1 2 0 A adc covered ch1 grounding postfilter_27_SPSstd](https://user-images.githubusercontent.com/14295481/68786833-5e678800-0638-11ea-8a9f-8647893d56d6.png)

**Comment by hartytp** [comment]
Thanks!

So, the conclusion is that with the fixed grounding we see no "glitches", short-term ADC offset changes or changes in the RMS noise as a function of TEC current, either with the barrel connector or the PoE. That's very good.

There is maybe a bit of extra noise on a ~seconds timescale at higher TEC current, which looks likely to be thermal. But, it's only an extra 10uK RMS or so, so pretty negligible.

Overall, that looks very good.

Can you post a temp co measurement please? Then we're done.

**Comment by pathfinder49** [comment]
Here are yesterdays temp co measurements.

Configuration as follows:
- 10k reference resistors directly connected to ch0&1
- TEC driver enabled, but set to not drive current (+ no load connected)
- Power from PoE
- Board placed on a hot-plate, covered by paper towel and a box
  - The resistors were left outside the box to achieve a more stable temperature.
  - Temperature was allowed to settle for ~20 minutes before measurements

Noise was consistent between the two measurements. The measured voltage changed by about 1000 LSB.


Hot plate set to 30°C
![PoE TEC noise 0 A T=30 ch1 grounding postfilter_27_SPS raw](https://user-images.githubusercontent.com/14295481/68865712-2d945b00-06eb-11ea-9ee8-de1c43203710.png)
![PoE TEC noise 0 A T=30 ch1 grounding postfilter_27_SPSstd](https://user-images.githubusercontent.com/14295481/68865728-308f4b80-06eb-11ea-9dff-2a3705df07bd.png)


Hot plate set to 70°C
![PoE TEC noise 0 A T=70 ch1 grounding postfilter_27_SPS raw](https://user-images.githubusercontent.com/14295481/68865833-60d6ea00-06eb-11ea-801a-0706a6614397.png)
![PoE TEC noise 0 A T=70 ch1 grounding postfilter_27_SPSstd](https://user-images.githubusercontent.com/14295481/68865845-63394400-06eb-11ea-9095-ee710673a360.png)

**Comment by hartytp** [comment]
Thanks @pathfinder49 Okay, I'm happy that this design is now really well tested and works beautifully. Thanks all

**Comment by hartytp** [comment]
So, that's something like 25LSB/K temp co.

A standard thermistor is approx 5e-2/K. So the 5ppm/K resistors we have on the board are 1e-4 less sensitive. If we assume the temp co is dominated by a single 5ppm/K resistor then we'd expect 1e-4K/K. That's a 20LSB/K temp co. In other words, that measurement looks roughly consistent with a naive estimate of the temp co for the design (assuming the ADC contributes negligibly).

Great!

NB with the board running at max temp lying flat on a desk, the ADC got to ~60C (TEC driver at 120C) in 25C ambient. That's 35C change in temp so we'd expect a total change in temperature measurement of 3.5mK.
