### ISSUE TITLE
Thermostat: request for comment

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#5]
I've sketched out a proposal for a temperature control EEM that I'm provisionally calling [Termostat](https://github.com/m-labs/sinara/wiki/Thermostat).

I'm interested in any comments that people have. Does that sound like something you'd use? Does the proposal match your needs? Any suggested improvements? etc...

**Comment by jordens** [comment]
Ignoring Zotino and looking at the generic use case: POE for me (1) solves the complete array of issues associated with cabling (connector, panel, power loss, cable, noise) between Thermostat and TEC/Thermistor, (2) fixes the powering question, i.e. the leeching issue actually leeching a significant amount of power from the Kasli tree, (3) represents a very good generic way to hook up EEMs that should not or can't use the EEM connector.

**Comment by gkasprow** [comment]
transferred the issue to the right repo.
