### ISSUE TITLE
PoE turns off and on

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#51]
@gkasprow we saw this on one of our thermostat boards. I'll ship it to you for investigation.

**Comment by hartytp** [comment]
It did stabilize and stay on eventually, but took quite a while for the switch to stop registering PoE faults

**Comment by gkasprow** [comment]
in my lab it works fine
Here is the plot. Blue - 12V
green - PoE voltage before DC/DC
![tek00001](https://user-images.githubusercontent.com/4325054/65880924-dc2a4980-e392-11e9-9154-1cb078593dbd.png)

**Comment by gkasprow** [comment]
The PoE voltage was measured with diff HV x100 probe

**Comment by hartytp** [comment]
There is clearly something marginal somewhere so it's only particular combinations of boards and switches that fail to work.

Shall I send you the switch as well?

**Comment by hartytp** [comment]
Actually, maybe first try it with the switch that @sbourdeauducq sent you? (Or see if you can reproduce this using the same stabilizer and swtich combination that he had?)

**Comment by gkasprow** [comment]
I still didn't get the package from @sbourdeauducq

**Comment by hartytp** [comment]
Okay, no problem. I'll send you the switch we used to reproduce this issue with. It's in use now, so will be a few days before I ship it.

**Comment by gkasprow** [comment]
Anyway, I go to ESTEC for space & quantum conference, will be back on Friday.

**Comment by hartytp** [comment]
Aah, ok. In that case, can you send me the Thermostat back and I'll do the tests.

Which tests would you like to see to debug this issue?

**Comment by gkasprow** [comment]
I have with me only one with broken CPU and DC/DC which will pass to Technosytem for reparation tomorrow.

**Comment by hartytp** [comment]
And broken ADC (the CPU applied 5V to the ADC via the digital outputs). So, most of the PCB is dead :(

I think you have two I sent you...one with the broken 3V3 SMPS (but working PoE) and one with a working SMPS but dodgy PoE.

**Comment by gkasprow** [comment]
yes, but one is at the WUT and I'm leaving tomorrow.

**Comment by hartytp** [comment]
Okay, well I need that one to test PoE as the other one doesn't display this issue. No worries if you can't ship it, we can wait until you get back.

**Comment by hartytp** [comment]
Can you ship this back to me so I can debug?

**Comment by gkasprow** [comment]
Yes, I will pass it to TS on Monday.
