### ISSUE TITLE
Review microprocessor connections

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#53]
Can someone sign off on these before the next round (eg @jordens @astro @sbourdeauducq )

**Comment by gkasprow** [comment]
the STM32CubeMX project is [here](https://github.com/sinara-hw/Thermostat/blob/master/STM32_F427_config.ioc)

**Comment by gkasprow** [comment]
SPI assignments:
SPI2: ADC
SPI3: extension header
SPI4: DAC0
SPI5: DAC1


Timers
TIM1_CH1: PWM_maxIPos0
TIM1_CH2: PWM_maxIPos1
TIM1_CH3: PWM_maxINeg0
TIM1_CH4: PWM_maxINeg1
TIM3_CH1: PWM_maxV0
TIM3_CH2: PWM_maxV1
TIM4_CH1: ADC CLKIO
TIM4_CH1: ADC SYNC


ADC assignments:

ADC1_IN0: TEC Vref0
ADC1_IN3: TEC Vref1
ADC1_IN4: DAC_FB0
ADC1_IN5: DAC_FB1
ADC1_IN6: ITEC0
ADC1_IN8: ITEC1
ADC1_IN9: extension header.3
ADC1_IN10: P5V0 sense
ADC1_IN12: TEC_U_meas0
ADC1_IN13: TEC_U_meas1

UART1: header
I2C1: EEPROM

**Comment by astro** [comment]
I cannot find `RMII_TXD0`. According to the [Datasheet](https://www.st.com/resource/en/datasheet/stm32f427zi.pdf), the only possible pin seems to be `PB12` which is used for ADC.

**Comment by gkasprow** [comment]
well, the STM32CubeMx says that PG13 is also possible
![obraz](https://user-images.githubusercontent.com/4325054/68812754-1d8d6480-0674-11ea-9d47-0faad6a08d31.png)

**Comment by astro** [comment]
Oh, I didn't recognize the second rectangle as the other half of the MCU. Continuing review...

**Comment by astro** [comment]
Looks good to me.

**Comment by hartytp** [comment]
@astro if you're happy with this, please close the issue. Thanks!

**Comment by hartytp** [comment]
@gkasprow my understanding is that the microprocessor has 3 ADCs, with muxes to give 24 channels. We should make sure to connect Vref0 to the same ADC as DAC_FB0, same for channel 1, to maximise accuracy.

**Comment by gkasprow** [comment]
Vref0 
![obraz](https://user-images.githubusercontent.com/4325054/69286575-e8dd5800-0bf3-11ea-88df-3adaf80a0108.png)

DAC FB0
![obraz](https://user-images.githubusercontent.com/4325054/69286608-feeb1880-0bf3-11ea-8ec8-a7a3a91ab30f.png)

Vref1
![obraz](https://user-images.githubusercontent.com/4325054/69286639-0d393480-0bf4-11ea-810e-c882a28d5d71.png)

DAC FB1
![obraz](https://user-images.githubusercontent.com/4325054/69286672-1f1ad780-0bf4-11ea-9986-236fc3c20788.png)

so we can assin all these inputs to ADC1 or ADC2.
