### ISSUE TITLE
v2.0 schematic review

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#54]
@gkasprow is there any chance of getting a schematic rc release of Thermostat for Monday? I'd really like to finish my review.

**Comment by hartytp** [comment]
@gkasprow okay, I believe all testing and reviews are now complete so we can finish the new hw rev.

What do you think the timeline is for getting these boards off to manufacture? Since the changes all seem to be quite small, hopefully we can do this quickly?

**Comment by gkasprow** [comment]
Most of the issues are already implemented. Give me 2 days to implement them all.

**Comment by hartytp** [comment]
Perfect! Thanks

**Comment by hartytp** [comment]
ping @gkasprow can we get this sent off to manufacture on Monday?

**Comment by hartytp** [comment]
@gkasprow I hear that the new boards are ready. Once you've smoke tested, can you send one of our board to M-Labs asap so they can finish the firmware? Thanks!
