### ISSUE TITLE
UART pins

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#6]
@gkasprow right now the USB UART is only exposed via test points. Can you add a pin-header for the next version so we can use it with something like https://www.amazon.co.uk/UART-CP2102-Module-Serial-Converter/dp/B00AFRXKFU

**Comment by hartytp** [comment]
also needs power and ground

**Comment by gkasprow** [comment]
the Thermostat has a pin header so you can use it without a problem.
![obraz](https://user-images.githubusercontent.com/4325054/51935891-3c817980-2407-11e9-891a-16876a00a8dd.png)

**Comment by gkasprow** [comment]
btw, a box with assembled Thermostats is laying since a few days on my desk. I didn't have time to play with them...

**Comment by hartytp** [comment]
@that look different to the rendering in the pdf release. Is the pdf out of date?

**Comment by hartytp** [comment]
Cool are those the boards we ordered? If so can you ship them?

**Comment by gkasprow** [comment]
Yes, I planned to make burn tests only.

**Comment by hartytp** [comment]
Ok cool. Well looking forward to getting my hands on them :)

**Comment by hartytp** [comment]
Please do make sure the release is up to date though

**Comment by gkasprow** [comment]
Oh, I've just noticed that this change was added after the boards were shipped for production.
 So will be available in next release.

**Comment by hartytp** [comment]
Makes sesne
