### ISSUE TITLE
extra EMI capacitors

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#60]
To avoid any rectification by the EMI diodes, let's add extra EMI capacitors like this:

![image](https://user-images.githubusercontent.com/21218399/69044910-b2ce8700-09ed-11ea-8902-418db762efac.png)

**Comment by gkasprow** [comment]
shouldn't they be added to GND? Otherwise large CM signal can still be rectified.

**Comment by hartytp** [comment]
Yep you’re right. Add a larger dm cap as well to avoid cm to dm conversion (or copy the caps from the rfi filter to make it two stage)

**Comment by gkasprow** [comment]
Can we stick with such design?
![obraz](https://user-images.githubusercontent.com/4325054/69287447-92254d80-0bf6-11ea-8b9b-2c11e973fb8c.png)
