### ISSUE TITLE
ref 2V5

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#61]
This currently looks to be driven by both the 24-bit ADC and the MCP1525T.

AFAICT it would be better to power the microprocessor ref from a 3V3 reference anyway: currently we have separate dividers for the DAC output going to the TEC driver/microprocessor. That will limit the accuracy of the TEC driver calibration. If we used a 3V3 microprocessor reference then we could scrap the divider for the microprocessor... 

![image](https://user-images.githubusercontent.com/21218399/69047129-62a5f380-09f2-11ea-8231-627ec551fdfc.png)

![image](https://user-images.githubusercontent.com/21218399/69047139-68033e00-09f2-11ea-8e49-72b463ff4ec1.png)

**Comment by hartytp** [comment]
Changing the microprocessor reference will also require changing the resistors used for the TEC current measurement. 
![image](https://user-images.githubusercontent.com/21218399/69047212-8cf7b100-09f2-11ea-9078-7cd5f0b23318.png)

**Comment by gkasprow** [comment]
The assembly variant makes the MCP1525 DNP so the CPU ADC is driven from the 24bit ADC.
We don't have any 3V3 reference. I would have to replace the MCP1525 with a 3V reference. I'm not sure if we gain a lot here. We will add yet another reference voltage that is not related to ADC reference nor DAC reference.

**Comment by hartytp** [comment]
I'd like to be able to have the same divider on the DAC outputs going to the microprocessor and TEC driver so we don't need to think about tolerances on the dividers.

I'd be happy with:
- generate a 3V0 (or 3V3) microprocessor reference by dividing the 5V0A rail with a resistive divider (IIRC the microprocessor has a ref buffer so this can be relatively high-Z)
- use a filtered version of the 3V3 SMPS rail for the microprocessor ADC reference.

**Comment by hartytp** [comment]
@gkasprow do you think we can get v2.0 ready to ship on Monday?

**Comment by hartytp** [comment]
ping @gkasprow when can we get this sent off?

**Comment by gkasprow** [comment]
I didn't look here for a while. Next time just write an email. All github issues mails land in dedicated folder. Yes, we can produce it on Monday.

**Comment by hartytp** [comment]
Great. Can you produce an RC before that so I can sign off on the final changes?

**Comment by gkasprow** [comment]
the reference input in STM32F4 is not buffered
![obraz](https://user-images.githubusercontent.com/4325054/69892314-7d3a6f80-1304-11ea-9e51-837d30150c66.png)

the easiest is to add opamp buffer (LMV321ILT) that we already use and remove MCP1525 to make space

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/69892370-0ea9e180-1305-11ea-9627-6d1644ef739b.png)

**Comment by gkasprow** [comment]
the DAC output would look like this.
![obraz](https://user-images.githubusercontent.com/4325054/69892388-3b5df900-1305-11ea-9d64-15be98a27350.png)

The 1k6 at the output isolates DAC from ADC current pulses caused by ADC sampling circuit

**Comment by hartytp** [comment]
Lgtm
