### ISSUE TITLE
DAC output divider

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#63]
![image](https://user-images.githubusercontent.com/21218399/69072990-6f433f80-0a24-11ea-97bd-5093cff07837.png)

This gives a 0 .. 2V5 output range. Don't we need 0 .. 3V for the TEC driver?

I guess we could just run this from a 3V0 reference and use the same reference for the microprocessor (with suitable decoupling).

**Comment by hartytp** [comment]
hmm...if we do use a 3V0 ref we'd still need a 5V0A rail for this (don't want to run the DAC directly from an SMPS if we can avoid it).

**Comment by gkasprow** [comment]
with 1k6 : 2k4 we get exactly 3V
