### ISSUE TITLE
Thermal sheets

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#66]
Try them with v 2.1 to see if we can conduct heat from the tec drivers to the enclosure

**Comment by gkasprow** [comment]
@hartytp how many v2 boards shall we produce?

**Comment by hartytp** [comment]
@gkasprow Thermostat v2.0 has arrived from TechnoSystem. The enclosures look great! Can't wait to try it.

Currently it doesn't have the thermal sheeting we previously discussed (to improve the heat conduction from the PCB to the case).

Can you recommend a PN for the thermal sheeting we should use and give some advice on how to install it/what we're trying to achieve (i.e. is the idea to just uniformly coat the PCB and also get a thin layer that will squish in the slot where the PCB mounts to the case to improve conductivity?).

Once the new FW is ready, we'll test the thermal performance both with and without the sheeting and see if it's worth it. If it is, the we should add it to the BOM.

**Comment by gkasprow** [comment]
I didn't see them. I'll ask TS for additional unit I could test. I have such sheets in my lab.
I'd try to use one of[ these](https://pl.farnell.com/w/c/zarzadzanie-chlodzeniem-i-temperatura/materialy-przenoszace-cieplo/materialy-termoprzewodzace?grubosc=1.524mm|2mm|2.032mm|2.54mm|3mm|3.175mm|3.18mm|3.2mm|4mm|4.1mm|5mm|5.08mm&range=inc-in-stock), just choose one with right thickness. Glue Alu foil on top to make the PCB  insertion feasible.

**Comment by hartytp** [comment]
Aah cool! Ok you have a play with it and tell us what you think we should do.

**Comment by hartytp** [comment]
Let me know if you need me to send you a Thermostat

**Comment by gkasprow** [comment]
I have one thermostat, just need an enclosure with panels. I will get them from TS on Monday. From you, I need a firmware that is able to provide the conditions I need. I can also attach tiny PT1000 to measure temperatures.

**Comment by hartytp** [comment]
Right now there isn’t any firmware for the v2 hardware (STM micro). M-Labs are planning to port their firmware. We can put this testing off until the new firmware is ready if it’s easier, there isn’t a rush on this...

**Comment by gkasprow** [comment]
OK, I can generate some simple code with CubeMX and make PWMs running to dissipate some power.
However if Mlabs firmware is coming soon, it's better to wait.

**Comment by sbourdeauducq** [comment]
The board gets surprisingly hot, with only 1 TEC connected.

**Comment by hartytp** [comment]
I assume it's comparable to the v1.0 hardware that we characterized before (several sets of ~85% efficient SMPSs add up to quite a bit of power dissipation)? See the thermal images we posted.

Once the firmware works well enough it would be great for @gkasprow to have a play with thermal conductive sheets as discussed above.

**Comment by gkasprow** [comment]
In a few days I will receive the multi-point thermometer so will do detailed analysis with thermal sheets and without them.

**Comment by hartytp** [comment]
Great!

**Comment by gkasprow** [comment]
I wrote a half a year ago about the multi-point thermometer. I received two such boxes a few days ago ...
![2020-10-11 22 06 11](https://user-images.githubusercontent.com/4325054/95689240-9c39ab80-0c0f-11eb-8624-479559c3b303.jpg)

**Comment by gkasprow** [comment]
@hartytp look [here ](https://github.com/sinara-hw/Thermostat/issues/73#issuecomment-719834216)
