### ISSUE TITLE
V2.0 testing

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#73]
On top of the tests we performed on v1.0, I suggest the following tests for v2.0:
- [x] Glue a couple of thermistors on the places we expect to be hottest (e.g. TEC driver). Run the unit at full power inside the case and look at the change in temperature. Do this with/without the thermal sheeting and using both PoE and a barrel connector.
- [ ] While taking the above measurement, monitor the ADC reading with a precision 10k resistor in place of a thermistor. Look for both step-changes in the ADC reading when the TEC is turned on and slower (thermal) changes as the unit heats up
- [ ]  Temperature stabilize a commercial optical cavity. Monitor the temperature using a witness thermistor and Keysight 7.5 digit DMM.

**Comment by gkasprow** [comment]
Measurement of temperatures inside of the enclosure is simple from one side and tricky from the other side. Usually, I use a set of tiny PT1000, thin wires, DMM and rotary switch. But this is problematic and takes a lot of time. To make my life easier, I designed a [simple box](https://github.com/gkasprow/temperature-logger/wiki) with various configurations of [sensors](https://github.com/gkasprow/temperature-logger/issues/1) that do exactly what we need. It took me 2 days including PCB, enclosure, 3D printing, and basic firmware. But this will pay off. 
The box will dump measurements to the SD card, serial port or via the MQTT.

**Comment by gkasprow** [comment]
I plan to produce 5 units for me ASAP. If sb wants, I can make a few more.

**Comment by gkasprow** [comment]
V2 photos 
![2020-05-13 23 31 46](https://user-images.githubusercontent.com/4325054/81870109-8303d480-9575-11ea-9566-b3efb3273eac.jpg)
![2020-05-13 23 33 05](https://user-images.githubusercontent.com/4325054/81870147-957e0e00-9575-11ea-8526-24c2d3eac372.jpg)

**Comment by astro** [comment]
I'm using the green output connectors which are usable through the enclosure. ~The labelings for TEC1/TEC2 on the board, and 0/1 on the enclosure should be swapped.~

Actually, it's the SENS pins that are swapped.

**Comment by gkasprow** [comment]
@astro open dedicated issue, please.

**Comment by gkasprow** [comment]
I finally got the multi-channel PT1000 measuring box, TECs, sensors, thermal sheets. I'm playing with parameters and Python scripts right now.

**Comment by gkasprow** [comment]
after playing with PoE switch the Thermostat stopped responding.. The PHY LEDs are on continuously, I see a startup message on the USB port. After some time the PHY LEDs go off.

**Comment by gkasprow** [comment]
I replaced the PHY and Ethernet works again.

**Comment by gkasprow** [comment]
I was using a 15W PoE switch before and nothing happened. Today I switched to 30W one and after a few plug-unplug cycles the PHY stopped to work

**Comment by jordens** [comment]
This looks so much like the issue on Stabilizer that it makes a PCB manufacturing error a bit unlikely (those are two different boards), right?

**Comment by gkasprow** [comment]
Exactly. The PoE and PHY circuit is identical in both cases.

**Comment by gkasprow** [comment]
the PHY Ethernet signals are protected using TVS diodes. Anyway, I will probe them with the scope during plug/unplug action.

**Comment by gkasprow** [comment]
the thermal test parameters:
tec = Client() #(host="localhost", port=6667)
tec.set_param("s-h", 0, "t0", 32651)
tec.set_param("s-h", 1, "t0", 32651)
tec.set_param("s-h", 0, "b", 3977)
tec.set_param("s-h", 1, "b", 3977)
tec.set_param("pwm", 0, "max_v", 5)
tec.set_param("pwm", 1, "max_v", 5)
tec.set_param("pwm", 0, "max_i_pos", 4)
tec.set_param("pwm", 1, "max_i_pos", 4)
tec.set_param("pwm", 0, "max_i_neg", 4)
tec.set_param("pwm", 1, "max_i_neg", 4)
tec.set_param_short("pwm", 0, -3)
tec.set_param_short("pwm", 1, -3)
tec.set_param("report mode", "off")

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/97764711-cfd16c80-1b0f-11eb-8a60-fb8fe8f05bd5.png)


10h50 - power on, network connection. The board was warm due to previous experiments
10h59 - execution of the script listed above.
11h05 - board enters thermal protection mode. The LM75 has some hysteresis which causes oscillations and periodic disabling of the power stage. 
11h15 - a small fan (40x40x10, 12V, 40mA) was placed partially covering one endcap. Some fraction of the flow passes via the enclosure cooling the PCB.
11h24 - the fan voltage was set to 6V, 23mA.
11h37 - the fan voltage was set to 4V, 15mA
11h43 - the fan voltage was set to 3V, 12mA; the fan placement changed slightly
11h45 - the fan voltage was set to 6V, 23mA

The board consumes 27.5... 29W of power, depending on the temperature inside.
I used external 12V power to not damage the Ethernet PHY by PoE.
That's why the PoE converter is not hot.

**Comment by gkasprow** [comment]
the conclusion is:
- even very small airflow drastically improves working conditions of the board.
- we need to replace the inductors with ones with smaller losses
- let's try with thermal sheets, but I do not expect drastic improvement
- we can fit small 25x25x8 or even x10 fan to esisting design. Fan control circuit is already there.

**Comment by gkasprow** [comment]
here is the raw data
[full power passive and fan.zip](https://github.com/sinara-hw/Thermostat/files/5468046/full.power.passive.and.fan.zip)

**Comment by gkasprow** [comment]
I installed a sandwich of the copper-filled thermal sheet, alu block, and again the sheet between inductors and the enclosure.
Another sheet was placed between the driver ICs and enclosure. Assembly of it is very problematic but let's see what we get. Yet another one connects PCB below the DC/DC with the enclosure. To make insertion possible, I placed mica pads on top of the sandwich.

**Comment by gkasprow** [comment]
It seems the thermal pads helped a lot. One of the enclosure sensors died during measurements, but we have two of them. It was misbehaving before.
At 1h38 the fan was turned on running at 6V/23mA
At 1h51 fan speed was ramped up, 12V/40mA
Power consumption is 29,7W
![obraz](https://user-images.githubusercontent.com/4325054/97767540-fa75f200-1b1c-11eb-98f6-9d6cd07d730e.png)


Next test will be with PoE supply

**Comment by gkasprow** [comment]
The raw data is here
[TH pads full power passive and fan.zip](https://github.com/sinara-hw/Thermostat/files/5468293/TH.pads.full.power.passive.and.fan.zip)

**Comment by gkasprow** [comment]
The PoE has its own thermal shutdown that activates after exceeding 95 degrees. 
![obraz](https://user-images.githubusercontent.com/4325054/97779454-79e7dd80-1b7e-11eb-9b02-1086d341bf2a.png)
1h17 - the script was executed

**Comment by gkasprow** [comment]
The AG5300 [datasheet](http://silvertel.com/images/datasheets/Ag5300-datasheet-smallest-30W-Power-Over-Ethernet-Plus-Module-PoEplusPD.pdf) says about 85degrees, I'm measuring the temperature on the inductor, not the IC, so that makes sense.

**Comment by hartytp** [comment]
@gkasprow okay, so thermal sheets and a bit of forced air let the unit run at max power dissipation while remaining at pretty low temperatures. As you note, we may also be able to make some (small?) improvements by looking for lower loss inductors.

But, how practical are these changes? Do we think they will work in practice/production?

I wonder if the most practical solution here would be to say that the compact version is intended for lower powers (e.g. using some software limiting); higher powers should use the EEM version with forced air cooling. Obviously if we can find a nice solution for making this version work at max power that would be great, but we'd need to avoid it without expensive machining or fragile assemblies.

FWIW the use cases I have in mind for this are mainly quite low powers...

**Comment by gkasprow** [comment]
Thermal sheets do not help that much in case of forced-air cooling. They lower the inductor temperature mostly. They are very problematic in assembly. So I recommend adding a small fan only. I ordered a few of them. It will fit easily.
![obraz](https://user-images.githubusercontent.com/4325054/97781252-4ca12c80-1b8a-11eb-8dd5-d182bb30ab91.png)
Even with reduced airflow, where the fan noise is minimal, the temperatures are acceptable
![obraz](https://user-images.githubusercontent.com/4325054/97781273-76f2ea00-1b8a-11eb-9371-d82d3d675c94.png)
At 2h25 I reduced the fan voltage. I will add PWM switch so the CPU will be able to regulate the fan speed.
I'm running it with 29W consumed from 12V rail.

**Comment by gkasprow** [comment]
Machining of single side of the enclosure is cheap. 0.5mm precision is enough and the most expensive part is the precise fixing of the extruded part. Since this is not the case, the current impact would be neglidgible. Fan would be fixed by 2 self-tapered screws.

**Comment by gkasprow** [comment]
we can also glue small heatsink on top of the inductors.

**Comment by gkasprow** [comment]
I just removed the thermal sheets, and with reduced air flow the temperatures are:
![obraz](https://user-images.githubusercontent.com/4325054/97781824-2da49980-1b8e-11eb-8060-582cf949e862.png)

**Comment by gkasprow** [comment]
I'm curious why the output inductors heat that much. They have 54mOhm resistance. The CMC chokes at the output have 20mOhm and they are not heating that much, They are dissipating nerarly the same amount of heat because there are two coils.
I will add more channels to study this issue.

**Comment by gkasprow** [comment]
They are thermally connected to the driver ICs, so it's quite possible that the inductors are simply acting as the ICs radiators :)

**Comment by gkasprow** [comment]
It's easy to check if switching losses or conduction losses dominate in the indctors. If we lower the current to a very low value, the inductor should be cold.

**Comment by gkasprow** [comment]
In steady-state we have 
![obraz](https://user-images.githubusercontent.com/4325054/97783389-af4cf500-1b97-11eb-83da-570b23fd2134.png)
which means the inductors are much hotter than the ICs. On the other side, The probe is glued to the top of the IC and to the inductor. And the RTh of inductor is much lower than plasitc package if the IC. We will need a tiy heatsink on top of the inductor anyway. Ignore the 2nd channel

**Comment by gkasprow** [comment]
reduction of output voltages from 3V to 1V drastically changes temperature distribution in the circuit. It looks like inductors do not heat due to switching losses.
![obraz](https://user-images.githubusercontent.com/4325054/97783798-47e47480-1b9a-11eb-80f5-59d5bf780866.png)
Ignore the 2nd channel

**Comment by gkasprow** [comment]
I attached a small heatsink to the inductors. It reduced the temperatures of:
- inductors by 18 degrees 
- driver ICs by 5 degrees
- PCB close to the drivers by 8 degrees.
- PoE by 8 degrees
- DC/DC by 4 degrees
It's a simple and low-cost solution so we should apply it. It obstructed the airflow so more air is passing closer to the PoE module and DC/DC converter, that's why their temperature also dropped.
This is steady-state
![obraz](https://user-images.githubusercontent.com/4325054/97784226-4b2d2f80-1b9d-11eb-8b91-caa73239d59f.png)

**Comment by hartytp** [comment]
@gkasprow how do you plan to make the fan work with the small enclosure? Will you machine an opening in the enclosure?

**Comment by gkasprow** [comment]
@hartytp I received the 35x35x10 fan. It fits nicely and leaves enough clearance for the air. I will machine the openings like in the drawing
![obraz](https://user-images.githubusercontent.com/4325054/98489013-7f9f8c00-222c-11eb-9bd9-4017b98b6b49.png)

I will do it on my CNC machine, install the fan and repeat all measurements.

**Comment by hartytp** [comment]
Nice. What's the additional cost of machining the enclosure? Where is the air intake? Grill on one of the panels? Are you also adding heat sinks to lower the thermal impedance?

**Comment by gkasprow** [comment]
The intake is above the fan. The outlet is on the side where TEC connectors are.
The cost of machining would be 2..3EUR @ 20pcs

**Comment by hartytp** [comment]
:) that's awesome.

Did you get a chance to measure the temperatures?

**Comment by dtcallcock** [comment]
Will you also test Thermostat in the Eurocard rack configuration (with and without forced air)?  Or is it just a safe assumption that if this config works, so will that?

**Comment by hartytp** [comment]
yeah, my expectation is that in a rack with some decent forced air cooling this will be absolutely fine

**Comment by gkasprow** [comment]
I will do tests. I'm still waiting for the machined enclosures. Once they arrive I will repeat tests in both configirations

**Comment by gkasprow** [comment]
I finally received the enclosures. All fits perfectly. It's time to finish tests and make the release.
![2021-03-18 12 35 13](https://user-images.githubusercontent.com/4325054/111620798-79777880-87e7-11eb-9f71-7bf977258d43.jpg)
![2021-03-18 12 35 26](https://user-images.githubusercontent.com/4325054/111620806-7d0aff80-87e7-11eb-89ff-a65508545d02.jpg)

**Comment by hartytp** [comment]
That looks nice! Will be interested to see how hot things end up, but it definitely looks the part.

Shame we loose the silk for the connectors, but I guess that's unavoidable.

**Comment by gkasprow** [comment]
the fan is loud at max RPM, the airflow is much higher than I used during thermal tests. I already added PWM control circuit.
These new endcaps were 3d-printed but will be laser-cut and attached using screws.
The silk will fit under connectors
![obraz](https://user-images.githubusercontent.com/4325054/111622294-4930d980-87e9-11eb-9f95-ab8a000fdf01.png)

**Comment by hartytp** [comment]
:+1:

**Comment by gkasprow** [comment]
Today I found some time and assembled the test suite. I connected the fan (12V version) to the 5V rail because there is no PWM circuit in v2.2. The fan spins slowly, it's less audible than my laptop in idle mode. However, it seems it is sufficient to cool down the electronics. Both outputs are running at 3A, one is 2.7V, another is 3V. The MEasured current is 2.8A in both channels. The thermostat is supplied from the PoE switch. After 13mins it achieved a steady state.
![obraz](https://user-images.githubusercontent.com/4325054/116829693-7cff6d00-aba5-11eb-95e8-39574c30a53c.png)

**Comment by gkasprow** [comment]
Moreover, the airflow inside is obstructed by 8 thin measurement cables and sensors.

**Comment by gkasprow** [comment]
An observation - without the USB cable attached, the LAN does not start and the upper red LED is lit.

**Comment by gkasprow** [comment]
Let's try it with a 12V fan supply. The noise dominates all the noise sources in my lab. The steady-state is achieved after 6 mins.
![obraz](https://user-images.githubusercontent.com/4325054/116830087-1596ec80-aba8-11eb-91df-bad3a1c693eb.png)

All temperatures dropped significantly. Only the TEC driver is 3 degrees cooler because it is on the bottom side of the PCB where there is no airflow.

**Comment by gkasprow** [comment]
I think the results are fully satisfying and we can make a new v2.2 release. The fan and mounting screws are added to the BOM.

**Comment by gkasprow** [comment]
The internal temperature sensor is placed just about the TEC drivers so we can use it to control the fan RPM and make sure we never exceed let's say 65 degrees. In most conditions that will result in low audible noise operation.
