### ISSUE TITLE
Ship with connectors?

### ISSUE THREAD

**Issue by dtcallcock** [sinara-hw/Thermostat#74]
Might be useful to ship with connectors as it saves everyone having to order them themselves?

I think it's this one:
https://www.digikey.com/product-detail/en/phoenix-contact/1803604/277-1164-ND/260532

They do a nice strain-relieved version too:
https://www.digikey.com/product-detail/en/phoenix-contact/1768936/277-13964-ND/4452032

**Comment by hartytp** [comment]
The mating part is already in the BOM (it’s on the schematic first page). I think TS just forgot to ship them. Probably worth mentioning to them. Otherwise I think we can close this, since there is no change required to the design

**Comment by dtcallcock** [comment]
I let Pawel know.
