### ISSUE TITLE
insufficient JTAG connector clearance

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Thermostat#75]
Probe cable cannot be connected because it bumps into the 2-pin connector next to the JTAG header.

![image](https://user-images.githubusercontent.com/720864/76079843-86606a00-5fe0-11ea-93c1-bff944973305.png)

**Comment by gkasprow** [comment]
right. the 2 pin connector should be kept DNP. I will also move it right by 6mm

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/111231365-6bf49f80-85e9-11eb-9bb7-b09f8851e7c1.png)
