### ISSUE TITLE
add dot to indicate JTAG connector polarity

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Thermostat#76]
Right now it is particularly confusing as the polarity dot of a nearby diode seems to indicate incorrect polarity for the JTAG connector.

**Comment by gkasprow** [comment]
replaced connector footprint 
![obraz](https://user-images.githubusercontent.com/4325054/111214600-68a1e980-85d2-11eb-8062-a2871e41f396.png)
