### ISSUE TITLE
SENS pins are swapped between channels

### ISSUE THREAD

**Issue by astro** [sinara-hw/Thermostat#79]
(v2 hardware)

The SENS pins on the green headers at the PCB end should be swapped between TEC1/TEC2 channels.

**Comment by astro** [comment]
The underlying swap is AIN0..4 of AD7172-2BRUZ in AFE.SchDoc.

Corresponding mapping in the firmware: https://git.m-labs.hk/M-Labs/thermostat/src/branch/master/src/channels.rs#L40

**Comment by gkasprow** [comment]
The SENS pins are assigned to the channels by firmware.
I will fix the AFE.SchDoc but keep compatibility with existing hardware.

**Comment by gkasprow** [comment]
fixed on schematics
