### ISSUE TITLE
testing - connection issue

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#80]
@jordens I have an issue with communicating with Thermostat over Ethernet
I used a recent elf file that converted to dfu and flashed the chip.
It pings it at 192.168.1.26 
I manage to open the port 23 but it does not react to commands.
I used both putty under windows and netcat under Linux.
The wiki says "telnet clients send binary data after connect. Enter \n once to invalidate the first line of input."
How does it translate to the commands I have to send?

**Comment by jordens** [comment]
I haven't done much with thermostat yet. @astro or @hartytp or @pathfinder49 ?

**Comment by hartytp** [comment]
We haven't touched v2.0 yet as we're waiting for a firmware rc.

**Comment by gkasprow** [comment]
I'm referring to the connection instruction on the M-labs wiki. So probably it's a question to @sbourdeauducq

**Comment by astro** [comment]
Known issue: https://git.m-labs.hk/M-Labs/thermostat/issues/2

I'm still researching its cause. Let me add the workaround to our Nix/Hydra build in the meanwhile...

**Comment by gkasprow** [comment]
Let me know when you generate binaries that work with TCP

**Comment by astro** [comment]
Seems to be fixed now.

**Comment by gkasprow** [comment]
@astro can you generate binaries for me, please? preferably dfu file.

**Comment by sbourdeauducq** [comment]
Binaries are automatically generated on our server whenever input repositories are modified. The latest ones would be https://nixbld.m-labs.hk/build/91375

**Comment by astro** [comment]
A link to the always latest build is atop of the firmware's README.

**Comment by astro** [comment]
(Resolved but I lack permissions to close this issue.)
