### ISSUE TITLE
parameter settings

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#82]
@astro I have issue with setting of NTC parameters
b works fine, but t0 gets modified

s-h
{"channel":0,"params":{"t0":2.9815e2,"r0":1e4,"b":3.977e3}}
{"channel":1,"params":{"t0":2.9815e2,"r0":1e4,"b":3.8e3}}
s-h 0 t0 3265.1
s-h
{"channel":0,"params":{"t0":3.53825e3,"r0":1e4,"b":3.977e3}}
{"channel":1,"params":{"t0":2.9815e2,"r0":1e4,"b":3.8e3}}
s-h 0 t0 32651
s-h
{"channel":0,"params":{"t0":3.292415e4,"r0":1e4,"b":3.977e3}}
{"channel":1,"params":{"t0":2.9815e2,"r0":1e4,"b":3.8e3}}

**Comment by hartytp** [comment]
this is a firmware issue not a hardware issue
