### ISSUE TITLE
PoE kills PHY

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#83]
It was already discovered in Stabilizer and confirmed in THermostat that some PoE switches kill the PHY.
This is a known problem:
https://e2e.ti.com/support/power-management/f/196/t/861446
They solved it by adding TVS, but we already have them.

**Comment by gkasprow** [comment]
Interesting APP note
http://ww1.microchip.com/downloads/en/AppNotes/00002157B.pdf

**Comment by gkasprow** [comment]
It looks like we need to add four limiting resistors

**Comment by gkasprow** [comment]
Anyway, this time the Thermostat survived plugging the RJ45. It may get damage during unplug due to transients. During life unplugging, a few hundreds of mA suddenly stops flowing via the isolation transformer. It's a lot of energy. Enough to damage the PHY

**Comment by jordens** [comment]
A couple other things I found:

"Note: “Bob-Smith termination does not apply for Power Over Ethernet (PoE) applications."

![image](https://user-images.githubusercontent.com/1338946/97778064-e52cb200-1b74-11eb-9e87-31e16d1da98e.png)

From [TI](https://www.ti.com/lit/an/snla079d/snla079d.pdf).

And there seem to be special magnetics for PoE. I would have thought that our RJ45 is well equipped to handle PoE. But maybe worth checking.

**Comment by gkasprow** [comment]
we are already using dedicated PoE transformer with passives.
![obraz](https://user-images.githubusercontent.com/4325054/97781985-347fdc00-1b8f-11eb-969f-952f3b925cdb.png)

**Comment by gkasprow** [comment]
Yesterday I didn't switch off the PoE switch but was plugging and unplugging the RJ45 cable.
During plugging, there is no voltage on the contacts.
But during unplugging, one of the contacts always disconnects first causing an imbalance in the transformer.
So I suspect that the PHY gets damaged during the disconnect of RJ45.

**Comment by gkasprow** [comment]
I connected the decent scope to Rx, Tx, AVDDPHY and tried hard plugging and unplugging the RJ45 and didn't manage to catch any transient that is higher than standard link FLP/NLP pulses.

**Comment by gkasprow** [comment]
the PoE, 5V buck and 3.3V buck converters are stable. I did a step load test and the overshoot is lower than 100..200mV

**Comment by gkasprow** [comment]
I mounted the broken PHY, but it does not have any signs of life. It does not emit even FLP/NLP pulses. I mounted back the working chip and it works again.

**Comment by hartytp** [comment]
@gkasprow are you happy that with the different TVS and resistors you are no longer able to damage the phy?

**Comment by gkasprow** [comment]
I ordered the D1213A-04V-7 TVS that has the same footprint. I want to install them and see if I manage to kill the PHY

**Comment by sbourdeauducq** [comment]
@gkasprow Did you do the test, and should we just replace the TVS with D1213A-04V-7 on the existing 2.0 boards to fix this problem?

**Comment by gkasprow** [comment]
Yes, I replaced the TVS. I tried hard but didn't manage to kill it.
I have two other designs with identical PHY and PoE circuits, also replaced the diodes and so far no issues.

**Comment by gkasprow** [comment]
I think we can close it.
