### ISSUE TITLE
Thermostat v2.2 changes

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#84]
The new release will have the following changes:
- [x] replace TEC inductors with ones having lower losses
- [x] add fan
- [x] add fan fixing holes to the enclosure
- [x] add PWM support for the fan
- [x] add PHY protection resistors and better-suited TVS
- [x] add 10x25x10 heatsink on top of the inductors. It improves the air flow distribution and significantly lowers components temperature.

**Comment by hartytp** [comment]
Track any other improvements from the EEM version.
- [x] improvements to PoE module layout for thermal performance

**Comment by dtcallcock** [comment]
On v2.0 the BOOT0 jumper (JP2) is not labelled on the silkscreen.  Not a huge deal but annoying to have to go through the schematic and figure it out.

**Comment by jbqubit** [comment]
- [x] Fix channel-crossed SENS inputs.

**Comment by jordens** [comment]
Pleas don't change that as long as it introduces incompatibilities and as long as there are unaddressed impacts on the firmware.

**Comment by gkasprow** [comment]
It can be fixed in firmware already

**Comment by jordens** [comment]
Exactly.

**Comment by gkasprow** [comment]
PoE thermal issues seem to be solved by a fan and a heatsink on top of the inductors which redirect part of the flow to the PoE module. I described it in #73

**Comment by gkasprow** [comment]
added heatsinks 
![obraz](https://user-images.githubusercontent.com/4325054/111223974-241c4b00-85de-11eb-804d-2a0af261007b.png)
