### ISSUE TITLE
DFU boot loader jumper location

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Thermostat#85]
DFU boot loader jumper is not accessible from exterior of Thermostat v2.0 stand-alone housing. Consider shifting jumper location to edge of board near micro USB and update panel.

**Comment by jordens** [comment]
Please don't do that. Make the software support booting into DFU.

**Comment by jbqubit** [comment]
https://git.m-labs.hk/M-Labs/thermostat/issues/26
