### ISSUE TITLE
Flashing firmware

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Thermostat#87]
Wiki lacks instructions for flashing firmware. From conversation with @gkasprow today.

On a Windows machine install [st.com](https://st.com) DfuSe USB device firmware upgrade (DFU) software. [link](https://www.st.com/en/development-tools/stsw-stm32080.html).  

- [build](https://git.m-labs.hk/M-Labs/thermostat/#user-content-building) firmware .elf 
- locate .elf here: ```target/thumbv7em-none-eabihf/release/thermostat```
- add jumper to Thermostat v2.0 across 2-pin jumper adjacent to JTAG connector
- cycle board power to put it in DFU update mode
- connect micro-USB to PC
- use DFU software to upload .elf to Thermostat uP
- remove jumper
- cycle power to leave DFU update mode

Comments anyone?

**Comment by gkasprow** [comment]
You need to convert .elf to .DFU first

**Comment by jbqubit** [comment]
I was able to directly use the ```thermostat.elf``` you gave me this afternoon.

**Comment by Jemetzner** [comment]
You can also use [dfu-util ](http://dfu-util.sourceforge.net/) to upload a .bin file, which can be found with the release of the latest [builds](https://nixbld.m-labs.hk/job/stm32/stm32/thermostat).

**Comment by hartytp** [comment]
IMHO this should be in the firmware repo not the hw repo.

**Comment by jbqubit** [comment]
@hartytp https://git.m-labs.hk/M-Labs/thermostat/pulls/20

**Comment by hartytp** [comment]
why are you tagging me?
