### ISSUE TITLE
D9s

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Thermostat#9]
@gkasprow I'd really like to be able to use D9 connectors/cables to connect Thermostat to the load. I suggest the following
- [ ] In the next revision, scrap the 12V, 3V3_MP and I2C from the IDC connector, leaving only TEC+ (3 pins) TEC- (3pins) SENSE (3 pins) and GND.
~- [ ] Please can you make a 4HP FP with cutouts for 2xD9 -> IDC connectors? That way, one can mount thermostat in an 8HP box with the breakout panel and run a short IDC to connect the D9 to Thermostat~

**Comment by jordens** [comment]
No need to design. Those panels are COTS.

**Comment by hartytp** [comment]
Cool. Do you have a PN.

In any case, I'd still like to change the header to a 9pin one by default (happy to leave the other pins so that one can populate a larger header if necessary).

**Comment by jordens** [comment]
Schroff 30849-750 for example.

**Comment by hartytp** [comment]
Nice, thanks!

**Comment by hartytp** [comment]
@gkasprow can you add one of those to the BOM along with a pair of D9 IDC adapters. Maybe mark them as DNP or something so they're not shipped by default.

**Comment by gkasprow** [comment]
@hartytp one can use only part of the IDC connector - the first 9 pins are exactly what we need and 9-wire ribbon cable can be used. If we change the connector, we would need to do the same for Zotino as well.

**Comment by hartytp** [comment]
I'd much prefer to change the header for a 9-pin one with only the pins we need. Getting the user to connect a 9-way ribbon cable to the IDC is a bit confusing and can be error-prone. Putting all those extra wires on Zotino was a mistake and should be fixed in the next revision of Zotino.

**Comment by jordens** [comment]
9-pin headers are very much non-standard.

**Comment by hartytp** [comment]
True. So what’s standard to use with idc d9s?

**Comment by gkasprow** [comment]
Since the PC-AT Epoque, [DB9 RS232](https://www.google.com/search?q=DB9+IDC&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiezbbcvYXjAhWQl4sKHcMUDXEQ_AUIECgB&biw=1216&bih=580#imgrc=IsUh855r1P1IoM:) was connected to IDC10 using 9 wire ribbon cable with the last contact non-used.

**Comment by hartytp** [comment]
That works for me as a solution.
