### ISSUE TITLE
Reversed output current direction

### ISSUE THREAD

**Issue by TopQuark12** [sinara-hw/Thermostat#90]
The output voltage polarity and current direction does not match what is printed on the front panel. 

Quoting the MAX1968 datasheet, when (VCTLI - VREF) > 0, VOS2> VOS1, so the Peltier_pos and Peltier_neg net labels in the schematics is a bit misleading.

**Comment by gkasprow** [comment]
right. Shall I call the signals Peltier 1, Peltier 2?

**Comment by TopQuark12** [comment]
I'm more concerned about the labels on the front panel, which should have the TECx+ and TECx- labels swap positions. As for the net names, renaming them or swapping net names would work imo.

**Comment by gkasprow** [comment]
OK, I swapped labels on schematics and also swapped panel labels
