### ISSUE TITLE
low losses PoE

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#95]
There are higher efficiency PoE [modules ](http://silvertel.com/images/datasheets/Ag5400-datasheet-high%20Efficiency-30W-Power-Over-Ethernet-Plus-Module-PoE+PD.pdf)available. They have the same pinout. We can use them to limit losses.

**Comment by jordens** [comment]
At that point the rectifier diodes will limit efficiency as well.

**Comment by gkasprow** [comment]
sure, but they work at 50V so the losses are much lower than the existing PoE module where the output rectification diode works at 12V

**Comment by jordens** [comment]
Ah, yes. I miscounted the zeros. We loose about 2% in the diodes.

**Comment by gkasprow** [comment]
The difference between AG5300 and AG5400 is that the latter uses the synchronous rectification

**Comment by gkasprow** [comment]
The fan solves issues with PoE, I'm not sure if it's worth replacing the PoE module. New issues may appear.
