### ISSUE TITLE
Test-point silkscreen lables

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/Thermostat#96]
Please add some labels to the power rail test-points.

![image](https://user-images.githubusercontent.com/14295481/111153031-56e82400-8589-11eb-8f05-1f3463ca6068.png)

**Comment by pathfinder49** [comment]
The round exposed copper pads would also be helpful
![image](https://user-images.githubusercontent.com/14295481/111156255-6ff2d400-858d-11eb-8a89-92ed55545caa.png)

**Comment by gkasprow** [comment]
instead of designator, I will place the net name

**Comment by gkasprow** [comment]
done 
![obraz](https://user-images.githubusercontent.com/4325054/111233364-26d26c80-85ed-11eb-8ef2-547a3fe66c50.png)
