### ISSUE TITLE
Thermostat 2.2 changelog

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Thermostat#97]
- replaced EOL buck converter #88 
- replaced EOL TVS #91 
- added SHDN resistor #94 
- fixed DAC PN issue #78 
- fixed VBUS label  #89 
- JTAG pin 1 dot #76 
- replaced TVS; added series resistors #83 
- replaced Zener diode with 1SMA5916BT3G #92 
- fixed input channels numbering #79 
- added heatsinks on top of inductors

**Comment by gkasprow** [comment]
- moved TACHO input to TIMER8 CH3 IC @jordens please confirm it's OK
- added PWM fan control, routed to TIMER8 CH4 OC @jordens please confirm it's OK

**Comment by jordens** [comment]
Looks good to me

**Comment by gkasprow** [comment]
- changed HW_REV

**Comment by gkasprow** [comment]
- added test point names

**Comment by gkasprow** [comment]
- swapped TEC labels #90 on schematic and front panel

**Comment by gkasprow** [comment]
- added fan and screws to the BOM

**Comment by dtcallcock** [comment]
What's the timeline for 2.2 release @gkasprow ?  Our 2.0s are working nicely but would be good to have some of the issues fixed for our next order.

**Comment by gkasprow** [comment]
@dtcallcock done
https://github.com/sinara-hw/Thermostat/releases/tag/v2.2rc2
